### ISSUE TITLE
remove unnecessary const declarations

### ISSUE THREAD

**Issue by dimitrilw** [avacore1337/OneLife#15]
Since implementing the new variant_count crate's VariantCount Derive macro, many (all?) of the related `const` variables can be removed. Some will be easy, like `TUTORIAL_STEP_SIZE`, which is created once & used once in the same file.
<img width="574" alt="image" src="https://github.com/avacore1337/OneLife/assets/5898931/1663048a-844c-443e-b1f9-80d3bf7c1e50">

Others will take a bit more work, like `WORK_SIZE`, which is imported in many files, so there will be more refactoring and risk of error.
<img width="852" alt="image" src="https://github.com/avacore1337/OneLife/assets/5898931/0334b5a9-d20f-4918-802f-e9ae6b564ebb">

**Comment by avacore1337** [comment]
most of these should probably be "if it compiles it works"
That's what I've really liked working with Rust on this project.

**Comment by dimitrilw** [comment]
Fair enough. Also, doubling back on it, I think these const values give some nice explicit readability to the code. I'm going to close this one out.

And my apologies for being a pedantic old jerk. I have many years of professional "step in and tweak the code to adhere to standards and/or optimize".... so some of my poking around here is just bad habits -- good habits in the workplace; bad when I'm stepping on others' toes.

Thank you for being patient with me.
