### ISSUE TITLE
justfile

### ISSUE THREAD

**Issue by dimitrilw** [avacore1337/OneLife#22]
Another item that I do not know if you will like or not: adding a [justfile](https://github.com/casey/just).

I always liked the *idea* of npm-scripts, but the actual behavior is quirky. Granted: there are not (yet) any npm-scripts inside `package.json` that contain any characters or behaviors that will trigger weird behaviors & artifacts, but it's a thing. So I moved from old-school `Makefile` (no fun) to `justfile` (very intuitive & powerful). I've also used `pyinvoke`, `Taskfile`, `Magefile`, and others that I'm forgetting; but I have personal preference for `justfile` -- it's just sooooo clean & easy. 😄 

Thoughts...?

**Comment by dimitrilw** [comment]
Made a `justfile`. Assuming the `just` program is installed, then typing `just` at prompt gives list of scripts. And `just SCRIPT` executes it. Pic shows `just test-js tier_0`, which expands to:
`WASM_BINDGEN_TEST_TIMEOUT=60 wasm-pack test --node -- --test tier_0`

Pic has arrows to commands I entered into terminal.
<img width="929" alt="image" src="https://github.com/avacore1337/OneLife/assets/5898931/3793057c-708c-461c-9b27-5ab24cb792b5">


Thoughts...?

**Comment by dimitrilw** [comment]
Adjusted recipe `test-js` to use param name `TEST` instead of `TESTS` and have default value of `ALL` instead of an empty string -- more clear.

<img width="874" alt="image" src="https://github.com/avacore1337/OneLife/assets/5898931/6c60586c-75c6-4823-81db-e98e66c65db7">

**Comment by avacore1337** [comment]
Looks way nicer than make files. As long as it's not the only alternative I'm all for it 👍

**Comment by dimitrilw** [comment]
Awesome! I'll put in a PR so others can use my `justfile`, too.

PR #24 closes this issue.

**Comment by dimitrilw** [comment]
For reference, the [just.systems docs](https://just.systems/man/en/) (also ref'd in readme) are excellent. [This cheat-sheet](https://cheatography.com/linux-china/cheat-sheets/justfile/) is solid, too.

And sorry for ping, but want to ensure you see this note, @avacore1337 . ...should you ever choose to use `just` in your other efforts (work/personal), then these are solid refs.

Oh, and I'm not using this feature in the OneLife justfile (yet), but the ability to hold something like this:

```just
hello-world:
    #!/usr/bin/env python3
    print('Hello from python!')
```

....game changer.

Ref: [just docs :: writing recipes in other languages](https://just.systems/man/en/chapter_41.html)
