### ISSUE TITLE
feature request: embed commit hash into published gh-pages distro

### ISSUE THREAD

**Issue by dimitrilw** [avacore1337/OneLife#5]
I am unsure how to achieve this with Rust, but it looks like either the [vergen](https://docs.rs/vergen/0.1.1/vergen/fn.vergen.html) crate or use of a compile-time environment variable (as ref'd in [this StackOverflow answer](https://stackoverflow.com/a/44407625)) may be solid options.

I will gladly look at adding this after resolving #4 . Perhaps a version stamp at the bottom of either the Info tab or the Options tab. Or even an invisible stamp added as a HTML comment string in the header/footer section.

**Comment by avacore1337** [comment]
Sounds like a good suggestion

**Comment by dimitrilw** [comment]
While tinkering with typos, I also mixed in this issue. 

Result is a little data box at bottom-right of the right sidebar. Debug box lies beneath it; otherwise it is bottom box.
<img width="292" alt="image" src="https://github.com/avacore1337/OneLife/assets/5898931/495cb68d-e0ea-4f77-9c75-aba2faa6cc42">

The `Build` line is the version found in `Cargo.toml` file and the date the running version was compiled.
The `Commit` line is the 7-char short-hash and the date that commit was made.

**Comment by dimitrilw** [comment]
Should note: this info is achieved via a `build.rs` script that just harvests the data & populates the environment variables. This means it doesn't update with the hot-reloader; only on initial compilation. In other words, when I do `npm start` to run the local server, that panel shows data accurate to the time of that initial compile performed when `npm start` was entered. However, if the server is left running & hot-reloading, this info will not get updated. I believe that `build.rs` is not hooked by the hot-reloader, but not 100% sure how to change that. For now, I'm going to mark this as "done" because the main goal (from my vantage) was some kind of data in the deployed game to help with debugging.

...but perhaps you also wish to embed this data into any debug output, logs, etc. Dunno; just goofing & learning Rust. 😂

**Comment by dimitrilw** [comment]
marking closed via PR #18

**Comment by dimitrilw** [comment]
I should add that the documentation for the `vergen` package was unclear to me and lacked the kind of "explain it like I'm 5" kind of examples that I really needed. So I played around enough to determine that the `all_build()` method (found in the `build.rs` file) only triggers the emitter to output env data with `BUILD` in it, like `VERGEN_BUILD_DATE`. That's why there are three calls in `build.rs` before the `emit_and_set()` method is called; each method is for one group of env variables to be set.

Also, I've edited the build.rs file to add comments, but will just include that in next PR.

**Comment by dimitrilw** [comment]
This is assuming you are ok with version info in a sidebar panel. I apologize for making assumptions. If you do not like that, I can change to wherever you prefer. The data is linked, so as you know, it's just a matter of moving the rendering wherever you prefer. 😄

**Comment by avacore1337** [comment]
Nah, I don't mind giving you some freedom. Only if we are talking about major game design issues will I want to discuss stuff before merging. But generally I'm willing to try stuff, this is a hobby project, so the important part is to learn.
